version: '3'
services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
