version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5050:5050"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
